In [1]:
import pandas as pd
import numpy as np

In [2]:
# Update filename if needed
file_path = "../data/sales.csv"
df = pd.read_csv(file_path, encoding="latin1")

print("Shape:", df.shape)
df.head()

Shape: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994,9994,9994,9994,9994,9994,9994,...,9994.000000,9994,9994,9994,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
unique,NaN,5009,1237,1334,4,793,793,3,1,531,...,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,9/5/2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,38,35,5968,37,37,5191,9994,915,...,NaN,3203,19,6026,1523,48,NaN,NaN,NaN,NaN
mean,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55190.379428,NaN,NaN,NaN,NaN,NaN,229.858001,3.789574,0.156203,28.656896
std,2885.163629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32063.693350,NaN,NaN,NaN,NaN,NaN,623.245101,2.225110,0.206452,234.260108
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1040.000000,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56430.500000,NaN,NaN,NaN,NaN,NaN,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90008.000000,NaN,NaN,NaN,NaN,NaN,209.940000,5.000000,0.200000,29.364000
max,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000

In [4]:
# Example column names: quantity, unit_price, order_date, product_name, region

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['revenue'] = df['Sales']

print("Total Revenue:", df['revenue'].sum())

Total Revenue: 2297200.8603000003

In [5]:
monthly_revenue = (
    df.groupby(pd.Grouper(key='Order Date', freq='M'))['revenue']
      .sum()
      .reset_index()
)

monthly_revenue['pct_growth'] = monthly_revenue['revenue'].pct_change() * 100
monthly_revenue.head()

C:\Users\julie\AppData\Local\Temp\ipykernel_56456\4025236836.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.groupby(pd.Grouper(key='Order Date', freq='M'))['revenue']

  Order Date    revenue   pct_growth
0 2014-01-31  14236.895          NaN
1 2014-02-28   4519.892   -68.252263
2 2014-03-31  55691.009  1132.131409
3 2014-04-30  28295.345   -49.192257
4 2014-05-31  23648.287   -16.423401

In [6]:
top_products = (
    df.groupby('Product Name')['revenue']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_products

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: revenue, dtype: float64

In [7]:
revenue_by_region = (
    df.groupby('Region')['revenue']
      .sum()
      .sort_values(ascending=False)
)

revenue_by_region

Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: revenue, dtype: float64

In [8]:
monthly_profit = (
    df.groupby(pd.Grouper(key='Order Date', freq='M'))['Profit']
      .sum()
      .reset_index()
)

C:\Users\julie\AppData\Local\Temp\ipykernel_56456\2179518552.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.groupby(pd.Grouper(key='Order Date', freq='M'))['Profit']

In [9]:
monthly_combined = monthly_revenue.merge(
    monthly_profit,
    on='Order Date'
)

monthly_combined['profit_margin_pct'] = (
    monthly_combined['Profit'] /
    monthly_combined['revenue']
) * 100

monthly_combined.head()

  Order Date    revenue   pct_growth     Profit  profit_margin_pct
0 2014-01-31  14236.895          NaN  2450.1907          17.210148
1 2014-02-28   4519.892   -68.252263   862.3084          19.078075
2 2014-03-31  55691.009  1132.131409   498.7299           0.895530
3 2014-04-30  28295.345   -49.192257  3488.8352          12.330068
4 2014-05-31  23648.287   -16.423401  2738.7096          11.581006

In [11]:
march_2014= df[(df["Order Date"].dt.month == 3)&(df["Order Date"].dt.year == 2014)]
march_2014.shape

(157, 22)

In [20]:
df.groupby([ df["Order Date"].dt.year, df["Order Date"].dt.month]).size()

Order Date  Order Date
2014        1              79
            2              46
            3             157
            4             135
            5             122
            6             135
            7             143
            8             153
            9             268
            10            159
            11            318
            12            278
2015        1              58
            2              64
            3             138
            4             160
            5             146
            6             138
            7             140
            8             159
            9             293
            10            166
            11            324
            12            316
2016        1              89
            2              83
            3             163
            4             170
            5             225
            6             199
            7             201
            8             176
            9             363
            10            196
            11            370
            12            352
2017        1             155
            2             107
            3             238
            4             203
            5             242
            6             245
            7             226
            8             218
            9             459
            10            298
            11            459
            12            462
dtype: int64

In [25]:
march_2014["Discount"].mean()

np.float64(0.16751592356687897)

In [26]:
df["Discount"].mean()

np.float64(0.15620272163297977)

In [33]:
march_2014.groupby(march_2014["Category"])["Sales"].sum()

Category
Furniture          14573.956
Office Supplies     8605.879
Technology         32511.174
Name: Sales, dtype: float64

In [34]:
march_2014.groupby(march_2014["Category"])["Profit"].sum()

Category
Furniture         -1128.6550
Office Supplies    1270.4133
Technology          356.9716
Name: Profit, dtype: float64